CREATE TABLE IF NOT EXISTS drama_list(
    id SERIAL PRIMARY KEY,
    movieId INTEGER REFERENCES movies(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS film_list(
    id SERIAL PRIMARY KEY,
    movieId INTEGER REFERENCES movies(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS trending_list(
    id SERIAL PRIMARY KEY,
    movieId INTEGER REFERENCES movies(id) ON DELETE CASCADE NOT NULL
);