INSERT INTO movies
    (title,year,country,summary,posterUrl,trailerUrl)
VALUES
    ('The adventure of Sinbad','','United States',
    '',
    '',
    ''),
    ('Troy','','United States',
    '',
    '',
    ''),
    ('Kingdom of Heaven','','United States',
    '',
    '',
    ''),
    ('The Gladiator','','United States',
    '',
    '',
    ''),
    ('Home Alone',1990,'United States',
    '',
    '',
    ''),
    ('Romance in the rain','','China',
    '',
    '',
    ''),
    ('Battle of Changsa','','China',
    '',
    '',
    ''),
    ('The Battleship Island','','South Korea',
    '',
    '',
    ''),
    ('Train to Busan','','South Korea',
    '',
    '',
    ''),
    ('Secret garden','','South Korea',
    '',
    '',
    ''),
    ('Hanamizuki',2010,'Japan','',
    '',
    ''),
    ('One litre of Tears',2010,'Japan',
    '',
    '',
    ''),
    ('Sky of Love',2007,'Japan',
    '',
    '',
    ''),
;