INSERT INTO movies
    (title,year,country,genres,summary,posterUrl,trailerUrl)
VALUES
    ('The adventure of Sinbad',1996,'Canada',
    ARRAY ['TV Series','Adventure','Fantasy'],
    'The series is a re-telling of the adventures of Sinbad from The Arabian Nights',
    'https://images-na.ssl-images-amazon.com/images/I/91JtCED4iAL._SL1500_.jpg',
    'https://www.youtube.com/embed/XaLv6M8CTmQ'),

    ('Troy',2004,'United States',
     ARRAY ['Film','History'],
    'An adaptation of Homer great epic, the films follows the assault on Troy by the United Greek forces and chronicles the fates of the men involves',
    'https://m.media-amazon.com/images/M/MV5BMTk5MzU1MDMwMF5BMl5BanBnXkFtZTcwNjczODMzMw@@._V1_.jpg',
    'https://www.youtube.com/embed/znTLzRJimeY'),

    ('Kingdom of Heaven',2005,'United States',
    ARRAY ['Film','History'],
    'Balian of Ibelin travels to Jerusalem during the Crusades of the 12th century, and there he finds himself as the defender of the city and its people.',
    'https://m.media-amazon.com/images/M/MV5BODczYmE3ZDYtZjIwNC00ZTJhLThkMGUtZDcyNzkyNWMyZDNiXkEyXkFqcGdeQXVyMTAwMzUyMzUy._V1_UY1200_CR85,0,630,1200_AL_.jpg',
    'https://www.youtube.com/embed/znTLzRJimeY'),

    ('The Gladiator',2000,'United States',
    ARRAY ['Film','Action','Adventure'],
    'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    'https://m.media-amazon.com/images/M/MV5BZTI4OTAyOWYtZTM1My00MjgwLWE1ZWQtNmEzYjE5NzQ5ZTQ1XkEyXkFqcGdeQXVyMTAyNjg4NjE0._V1_SY1000_CR0,0,666,1000_AL_.jpg',
    'https://www.youtube.com/embed/owK1qxDselE'),

    ('Home Alone',1990,'United States',
    ARRAY ['Film','Comedy','Family'],
    'An eight-year-old troublemaker must protect his house from a pair of burglars when he is accidentally left home alone by his family during Christmas vacation.',
    'https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
    'https://www.youtube.com/embed/owU3lMxd6jI'),

    ('Romance in the rain',2001,'China',
    ARRAY ['TV Series','History','Romance'],
    'The story is of how Lu Yi Ping (Vicki Zhao) tries to take revenge for her mothers sufferings and her, while torn between trying to find the meaning of love and forgiveness in her disfigured world.',
    'https://i.mydramalist.com/Mjqzrf.jpg',
    'https://www.youtube.com/embed/uEdoHpXU-Mo'),

    ('Battle of Changsa',2014,'China',
    ARRAY ['TV Series','History','Romance'],
    'Story about an ordinary family in Changsha, Hunan Province, China, coping with the Anti-Japanese war between 1938 and 1945, reflecting Chinese peoples lives during that ill-fated period.',
    'https://upload.wikimedia.org/wikipedia/en/c/c1/Battle_of_Changsha_Drama_Series_Poster.jpg',
    'https://www.youtube.com/embed/Hn9DSrYX1ak'),

    ('Meteor Garden',2018,'China',
    ARRAY ['TV Series','School','Romance'],
    'Based on the Japanese shojo manga series Boys Over Flowers (Hana Yori Dango) written by Yoko Kamio, and a remake of the 2001 Taiwanese series of the same name',
    'https://i.mydramalist.com/NrEDyc.jpg',
    'https://www.youtube.com/embed/87Q8hTratnM'),

    ('The Battleship Island',2017,'South Korea',
    ARRAY ['Film','Action','Drama','History'],
    'During the Japanese colonial era, roughly 400 Korean people, who were forced onto Battleship Island to mine for coal, attempt to a dramatic escape.',
    'https://m.media-amazon.com/images/M/MV5BZDEwMDIxYzMtMGNhNC00MjJkLTkyODktOWUxMjlhYzBlMGE0XkEyXkFqcGdeQXVyNjQ3ODkxMjE@._V1_UY1200_CR106,0,630,1200_AL_.jpg',
    'https://www.youtube.com/embed/ZgOff3LJhWg'),

    ('Train to Busan',2016,'South Korea',
    ARRAY ['Film','Action','Thriller'],
    'While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan.',
    'https://i.mydramalist.com/xklBrf.jpg',
    'https://www.youtube.com/embed/pyWuHv2-Abk'),

    ('A Millionaire First Love',2006,'South Korea',
    ARRAY ['Film', 'Romance'],
    'Focuses on the boys struggle with a clause in his grandfathers will that says he will only get his inheritance if he graduates from a high school in the country. Relocated into the mountains, Hyeon finds puppy love with a naive country girl. Can love change the spoilt urbanite and awaken his gentler side?',
    'https://i.mydramalist.com/LaElMf.jpg',
    'https://www.youtube.com/embed/k-JQ797aBwc'),

    ('Secret garden',2010,'South Korea',
    ARRAY ['TV Series','Romance','Melodrama'],
    'A rationalizing Cinderella story between Gil Ra-im (Ha Ji-won), a stuntwoman, and Kim Joo-won (Hyun Bin), a high-end department store CEO.',
    'https://i.mydramalist.com/5Q5RYf.jpg',
    'https://www.youtube.com/embed/NaXPWhUDYe0'),

    ('Hanamizuki',2010,'Japan',
    ARRAY ['Film','Drama','Romance'],
    'A 2010 Japanese romance drama film inspired by the lyrics of a love song of the same name by Yo Hitoto. ',
    'https://i.mydramalist.com/MRrgMc.jpg',
    'https://www.youtube.com/embed/zPpWDkhg8BA'),

    ('Kimi ni Tokore (Reaching you)',2010,'Japan',
    ARRAY ['Film','Drama','School','Romance'],
    'Well-meaning, but socially awkward, Sawako Kuronuma is nicknamed Sadako by her classmates because of her similar hair cut with the main character from the horror movie "Ring." Her life takes a turn for the better, however, when Shota Kazehaya, the most popular boy in school, falls for her.',
    'https://i.mydramalist.com/dG15Gf.jpg',
    'https://www.youtube.com/embed/aBwfyKpjCOw'),

    ('One litre of Tears',2005,'Japan',
    ARRAY ['TV Series','Drama','School','Romance','Melodrama'],
    'Based on a true story of a 15-year-old girl named Aya Kito, who suffered from degenerative disease and died at the age of 25.',
    'https://i.mydramalist.com/QY0R2_4f.jpg',
    'https://www.youtube.com/embed/vnmdzY-pbGg'),

    ('Sky of Love',2007,'Japan',
    ARRAY ['Film','Drama','School','Romance'],
    'Mika is in her first year of high school. While Mika accidentally met a flashily dressed boy called Hiro at school, she turns and flees. They soon fall in love each other. Their days pass happily, but the trouble is coming to them.',
    'https://i.mydramalist.com/QY0R2_4f.jpg',
    'https://www.youtube.com/embed/iVOlYspDDgg'),

    ('Dreamy eyes',2020,'Vietnam',
    ARRAY ['Film','Drama','Romance'],
    'A movie tells the one sided love story of young man - Ngan for his girlfriend from childhood - Ha Lan',
    'https://nextphim.com/wp-content/uploads/2019/08/mat-biec.jpg',
    'https://www.youtube.com/embed/ITlQ0oU7tDA'),

    ('Blood Letter',2012,'Vietnam',
    ARRAY ['Film','Action','Fantasy'],
    'Adapted from a popular novel Buc Huyet Thu by Bui Anh Tan, based on the life of Nguyễn Anh Vu, a Royal court officer during the era of Emperor Le Thanh Tong',
    'https://nekonekomovielitterbox.files.wordpress.com/2013/04/thien-menh-anh-hung-poster.jpg',
    'https://www.youtube.com/embed/kiTeyH3xASE'),

    ('Yellow Flowers on the Green Grass',2015,'Vietnam',
    ARRAY ['Film','Family'],
    'Set in the countryside village of Vietnam, Yellow Flowers on the Green grass is a touching tale of innocent love, friendships and brotherhood',
    'https://upload.wikimedia.org/wikipedia/en/7/74/Yellow_Flowers_on_the_Green_Grass_poster.jpg',
    'https://www.youtube.com/embed/wmjiCP6R-7I'),

    ('The Immortal',2018,'Vietnam',
    ARRAY ['Film','Mystery'],
    'The twelfth feature film by Victor Vu, it tells the story of a man who has lived across three centuries after making himself immortal through dark magic.',
    'https://thegioidienanh.vn/stores/news_dataimages/thanhtan/092018/22/11/4552_Immortal_MainPosster.jpg',
    'https://www.youtube.com/embed/6VEVPtFDN_U'),

    ('The Third Wife',2018,'Vietnam',
    ARRAY ['Film','Drama'],
    'Set in the 19th century, it follows a 14-year-old girl who becomes the third wife to a landowner in rural northern Vietnam.',
    'https://m.media-amazon.com/images/M/MV5BNzIzYjZiOTktZTEyZi00NWEyLWFkMDMtNTczODU5ZjZjM2Y1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
    'https://www.youtube.com/embed/e3Gr7r7yWU8'),

    ('Rom',2019,'Vietnam',
    ARRAY ['Film','Crime','Drama'],
    'Movie story revolves around the life, fate of street children, homeless, specializing in selling lottery results every afternoon',
    'https://m.media-amazon.com/images/M/MV5BYjQ1MDk1YWUtODRhMS00ZDJjLTgxNGEtOWM0Mjk1MjU4MTlhXkEyXkFqcGdeQXVyMzQxMzk5NjY@._V1_.jpg',
    'https://www.youtube.com/embed/XRm1P7oGpMQ')
;