INSERT INTO reviews
    (movieId,userId,comment,rating)
VALUES
    (1,1,'It was an excelent movie',5),
    (1,2,'Nice work.Can anybody recommend me other movies like this?',3),
    (1,3,'Not my favorite',2),
    (2,4,'It was an excelent movie',5),
    (2,5,'Nice work.Can anybody recommend me other movies like this?',3),
    (2,6,'Not my favorite',2),
    (3,7,'It was an excelent movie',5),
    (3,8,'Nice work.Can anybody recommend me other movies like this?',3),
    (3,9,'Not my favorite',2),
    (4,9,'It was an excelent movie',5),
    (4,4,'Nice work.Can anybody recommend me other movies like this?',3),
    (4,2,'Not my favorite',2),
    (5,5,'It was an excelent movie',5),
    (5,7,'Nice work.Can anybody recommend me other movies like this?',3),
    (5,1,'Not my favorite',2),
    (6,3,'It was an excelent movie',5),
    (6,9,'Nice work.Can anybody recommend me other movies like this?',3),
    (6,2,'Not my favorite',2),
    (7,1,'It was an excelent movie',5),
    (7,4,'Nice work.Can anybody recommend me other movies like this?',3),
    (7,3,'Not my favorite',2),
    (8,7,'It was an excelent movie',5),
    (8,2,'Nice work.Can anybody recommend me other movies like this?',3),
    (8,1,'Not my favorite',2),
    (9,5,'It was an excelent movie',5),
    (9,8,'Nice work.Can anybody recommend me other movies like this?',3),
    (9,11,'Not my favorite',2),
    (10,10,'It was an excelent movie',5),
    (10,1,'Nice work.Can anybody recommend me other movies like this?',3),
    (10,5,'Not my favorite',2),
    (11,1,'It was an excelent movie',5),
    (11,3,'Nice work.Can anybody recommend me other movies like this?',3),
    (11,6,'Not my favorite',2),
    (12,2,'It was an excelent movie',5),
    (12,8,'Nice work.Can anybody recommend me other movies like this?',3),
    (12,4,'Not my favorite',2),
    (13,7,'It was an excelent movie',5),
    (13,1,'Nice work.Can anybody recommend me other movies like this?',3),
    (13,9,'Not my favorite',2),
    (14,1,'It was an excelent movie',5),
    (14,3,'Nice work.Can anybody recommend me other movies like this?',3),
    (14,5,'Not my favorite',2),
    (15,7,'It was an excelent movie',5),
    (15,9,'Nice work.Can anybody recommend me other movies like this?',3),
    (15,2,'Not my favorite',2),
    (16,4,'It was an excelent movie',5),
    (16,6,'Nice work.Can anybody recommend me other movies like this?',3),
    (16,8,'Not my favorite',2),
    (17,10,'It was an excelent movie',5),
    (17,9,'Nice work.Can anybody recommend me other movies like this?',3),
    (17,5,'Not my favorite',2),
    (18,7,'It was an excelent movie',5),
    (18,1,'Nice work.Can anybody recommend me other movies like this?',3),
    (18,3,'Not my favorite',2),
    (19,6,'It was an excelent movie',5),
    (19,4,'Nice work.Can anybody recommend me other movies like this?',3),
    (19,8,'Not my favorite',2),
    (20,1,'It was an excelent movie',5),
    (20,3,'Nice work.Can anybody recommend me other movies like this?',3),
    (20,5,'Not my favorite',2),
    (21,7,'It was an excelent movie',5),
    (21,2,'Nice work.Can anybody recommend me other movies like this?',3),
    (21,8,'Not my favorite',2),
    (22,4,'It was an excelent movie',5),
    (22,6,'Nice work.Can anybody recommend me other movies like this?',3),
    (22,1,'Not my favorite',2)
;